var platformList = [
			{'key': 'AFTV', 'name': 'AfreecaTV台灣', 'sUrl': 'http://afreecatv.com.tw/{ID}', 'vUrl': 'http://www.afreecatv.com.tw/{ID}/popout?type=share', 'cUrl': 'http://www.afreecatv.com.tw/live_chat.php?id={ID}'},
			{'key': 'AFTVN', 'name': 'AfreecaTV國際', 'sUrl': 'http://afreeca.tv/{ID}', 'vUrl': 'https://gaftvstatic.afreeca.tv/swf/LivePlayer.swf?id={ID}&s=embed', 'cUrl': 'http://www.afreeca.tv/channel/live_chat.php?id={ID}'},
			{'key': 'BEAM', 'name': 'Beam', 'sUrl': 'https://beam.pro/{ID}', 'vUrl': 'https://beam.pro/embed/player/{ID}', 'cUrl': 'https://beam.pro/embed/chat/{ID}'},
			{'key': 'BRK', 'name': 'Breakers', 'sUrl': 'https://breakers.tv/{ID}', 'vUrl': 'https://breakers.tv/embed/video/{ID}', 'cUrl': 'https://breakers.tv/popout/chat/{ID}'},
			{'key': 'CC', 'name': 'ConnectCast', 'sUrl': 'http://www.connectcast.tv/{ID}', 'vUrl': 'http://www.connectcast.tv/embed/{ID}', 'cUrl': 'http://www.connectcast.tv/{ID}/chat'},
			{'key': 'HIT', 'name': 'Hitbox', 'sUrl': 'http://www.hitbox.tv/{ID}', 'vUrl': 'http://www.hitbox.tv/embed/{ID}?popout=true&autoplay=true', 'cUrl': 'http://www.hitbox.tv/embedchat/{ID}?autoconnect=true'},
			{'key': 'LH', 'name': 'LiveHouse', 'sUrl': 'https://livehouse.in/channel/{ID}', 'vUrl': 'https://livehouse.in/embed/channel/{ID}/video', 'cUrl': 'https://livehouse.in/embed/channel/{ID}/chatroom'},
			{'key': 'STUP', 'name': 'Streamup', 'sUrl': 'https://streamup.com/{ID}', 'vUrl': 'https://streamup.com/{ID}/embeds/video', 'cUrl': 'https://streamup.com/{ID}/embeds/chatonly'}, 
			{'key': 'TTV', 'name': 'TwitchTV', 'sUrl': 'https://www.twitch.tv/{ID}', 'vUrl': 'https://player.twitch.tv/?channel={ID}', 'cUrl': 'https://www.twitch.tv/{ID}/chat'},
			{'key': 'UST', 'name': 'Ustream', 'sUrl': 'http://www.ustream.tv/channel/{ID}', 'vUrl': 'http://www.ustream.tv/embed/{ID}', 'cUrl': 'http://www.ustream.tv/socialstream/{ID}?siteMode=1'},
			{'key': 'VL', 'name': 'VaughnLive', 'sUrl': 'https://vaughnlive.tv/{ID}', 'vUrl': 'https://vaughnlive.tv/embed/video/{ID}', 'cUrl': 'https://vaughnlive.tv/popout/chat/{ID}'},
			//{'key': 'VL', 'name': 'VaughnLive', 'sUrl': 'https://vaughnlive.tv/{ID}', 'vUrl': 'http://live.sk-knower.com/vlurl.php?live={ID}', 'cUrl': 'https://vaughnlive.tv/popout/chat/{ID}'},
			{'key': 'YT', 'name': 'Youtube', 'sUrl': 'https:////www.youtube.com/watch?v={ID}', 'vUrl': 'https://www.youtube.com/embed/{ID}?autoplay=true', 'cUrl': 'https://www.youtube.com/live_chat?is_popout=1&v={ID}&embed_domain=darkertb.github.io'},
		];	